####


POST http://localhost:3000/register/
Content-Type: application/json


{
    "username" : "Sai",
    "password" : "Kishore12345"
}

#####


POST http://localhost:3000/login/
Content-Type: application/json 

{
    "username" : "Sai",
    "password" : "Kishore12345"
}